import { v4 as uuidv4 } from 'uuid';
import crypto from 'crypto';
import database from '../../utils/database';
import logger from '../../utils/logger';
import {
  AgentMission,
  AgentArtifact,
  AgentApproval,
  ValidationStatus,
  MissionStatus
} from '../../types';

export interface PublishResult {
  published_artifacts: AgentArtifact[];
  cdn_urls: string[];
  disclosures_added: string[];
  tracking_setup: TrackingRecord[];
  events_emitted: string[];
}

export interface TrackingRecord {
  tracking_id: string;
  artifact_id: string;
  tracking_type: string;
  metadata: Record<string, unknown>;
}

export interface Disclosure {
  type: string;
  content: string;
  position: 'header' | 'footer' | 'inline';
}

export class PublisherService {
  private readonly CDN_BASE_URL = process.env.CDN_URL || 'https://cdn.example.com';

  async publishArtifacts(
    mission: AgentMission,
    artifacts: AgentArtifact[]
  ): Promise<PublishResult> {
    logger.info('Publisher: Starting artifact publishing', {
      missionId: mission.id,
      artifactCount: artifacts.length
    });

    const publishedArtifacts: AgentArtifact[] = [];
    const cdnUrls: string[] = [];
    const disclosuresAdded: string[] = [];
    const trackingSetup: TrackingRecord[] = [];
    const eventsEmitted: string[] = [];

    await this.updateMissionStatus(mission.id, MissionStatus.PUBLISHING);

    for (const artifact of artifacts) {
      if (artifact.validation_status === ValidationStatus.FAILED) {
        logger.warn('Publisher: Skipping failed artifact', {
          artifactId: artifact.id
        });
        continue;
      }

      const validatedArtifact = await this.prePublishValidation(artifact, mission);
      
      const disclosures = await this.injectDisclosures(validatedArtifact, mission);
      disclosuresAdded.push(...disclosures.map(d => d.content));

      const contentWithDisclosures = this.addDisclosuresToContent(
        validatedArtifact,
        disclosures
      );

      const checksum = this.calculateChecksum(contentWithDisclosures);
      const cdnUrl = await this.deployToCDN(artifact.id, contentWithDisclosures);
      cdnUrls.push(cdnUrl);

      const publishedArtifact = await this.recordPublication(
        validatedArtifact,
        cdnUrl,
        checksum,
        mission.created_by
      );
      publishedArtifacts.push(publishedArtifact);

      const trackingRecord = await this.setupTracking(
        publishedArtifact.id,
        mission,
        'publication'
      );
      trackingSetup.push(trackingRecord);

      eventsEmitted.push(`artifact.published:${artifact.id}`);
    }

    eventsEmitted.push('agent.artifact.published');

    logger.info('Publisher: Publishing completed', {
      missionId: mission.id,
      publishedCount: publishedArtifacts.length,
      failedCount: artifacts.length - publishedArtifacts.length
    });

    return {
      published_artifacts: publishedArtifacts,
      cdn_urls: cdnUrls,
      disclosures_added: disclosuresAdded,
      tracking_setup: trackingSetup,
      events_emitted: eventsEmitted
    };
  }

  private async prePublishValidation(
    artifact: AgentArtifact,
    mission: AgentMission
  ): Promise<AgentArtifact> {
    logger.debug('Publisher: Pre-publish validation', { artifactId: artifact.id });

    if (!artifact.validation_status || artifact.validation_status === ValidationStatus.PENDING) {
      throw new Error(`Artifact ${artifact.id} has not been validated`);
    }

    if (artifact.validation_status === ValidationStatus.FAILED) {
      throw new Error(`Artifact ${artifact.id} failed validation and cannot be published`);
    }

    const content = typeof artifact.content === 'string' ?
      JSON.parse(artifact.content) : artifact.content;

    if (!content || Object.keys(content).length === 0) {
      throw new Error(`Artifact ${artifact.id} has no content`);
    }

    return artifact;
  }

  private async injectDisclosures(
    artifact: AgentArtifact,
    mission: AgentMission
  ): Promise<Disclosure[]> {
    const disclosures: Disclosure[] = [];

    disclosures.push({
      type: 'generation_disclosure',
      content: 'This content was generated by an AI agent',
      position: 'footer'
    });

    disclosures.push({
      type: 'mission_reference',
      content: `Mission: ${mission.objective.substring(0, 50)}...`,
      position: 'footer'
    });

    if (mission.context_package?.user_role) {
      disclosures.push({
        type: 'agent_role',
        content: `Generated for role: ${mission.context_package.user_role}`,
        position: 'inline'
      });
    }

    return disclosures;
  }

  private addDisclosuresToContent(artifact: AgentArtifact, disclosures: Disclosure[]): string {
    const content = typeof artifact.content === 'string' ?
      JSON.parse(artifact.content) : artifact.content;

    const footerDisclosures = disclosures
      .filter(d => d.position === 'footer')
      .map(d => d.content)
      .join(' | ');

    const inlineDisclosures = disclosures
      .filter(d => d.position === 'inline')
      .map(d => `[${d.content}]`)
      .join(' ');

    if (footerDisclosures) {
      content.footer = content.footer || {};
      content.footer.disclosures = footerDisclosures;
    }

    if (inlineDisclosures) {
      content.inline_disclosures = inlineDisclosures;
    }

    content.metadata = content.metadata || {};
    content.metadata.disclosures_added = disclosures.map(d => d.type);
    content.metadata.published_at = new Date().toISOString();

    return JSON.stringify(content);
  }

  private calculateChecksum(content: string): string {
    return crypto.createHash('sha256').update(content).digest('hex');
  }

  private async deployToCDN(artifactId: string, content: string): Promise<string> {
    logger.debug('Publisher: Deploying to CDN', { artifactId });

    const cdnPath = `artifacts/${artifactId}/${Date.now()}.json`;
    const cdnUrl = `${this.CDN_BASE_URL}/${cdnPath}`;

    await new Promise(resolve => setTimeout(resolve, 100));

    logger.info('Publisher: Deployed to CDN', { artifactId, cdnUrl });

    return cdnUrl;
  }

  private async recordPublication(
    artifact: AgentArtifact,
    cdnUrl: string,
    checksum: string,
    publishedBy: string
  ): Promise<AgentArtifact> {
    const sizeBytes = JSON.stringify(artifact.content).length;

    const result = await database.query(
      `UPDATE agent_artifacts 
       SET published_at = $1,
           published_by = $2,
           cdn_url = $3,
           size_bytes = $4,
           checksum = $5,
           metadata = metadata || $6
       WHERE id = $7
       RETURNING *`,
      [
        new Date(),
        publishedBy,
        cdnUrl,
        sizeBytes,
        checksum,
        JSON.stringify({ last_published_at: new Date().toISOString() }),
        artifact.id
      ]
    );

    return result.rows[0];
  }

  private async setupTracking(
    artifactId: string,
    mission: AgentMission,
    trackingType: string
  ): Promise<TrackingRecord> {
    const trackingRecord: TrackingRecord = {
      tracking_id: uuidv4(),
      artifact_id: artifactId,
      tracking_type: trackingType,
      metadata: {
        mission_id: mission.id,
        tenant_id: mission.tenant_id,
        workspace_id: mission.workspace_id,
        published_at: new Date().toISOString()
      }
    };

    logger.debug('Publisher: Tracking setup', trackingRecord);

    return trackingRecord;
  }

  async requestApproval(
    mission: AgentMission,
    artifactIds: string[],
    requestedBy: string
  ): Promise<AgentApproval> {
    logger.info('Publisher: Requesting approval', {
      missionId: mission.id,
      artifactCount: artifactIds.length
    });

    const approvalId = uuidv4();
    const dueAt = new Date();
    dueAt.setMinutes(dueAt.getMinutes() + (mission.approval_policy.timeout_minutes || 30));

    const result = await database.query(
      `INSERT INTO agent_approvals 
       (id, mission_id, artifact_ids, requested_by, requested_at, status, priority, due_at, notification_sent)
       VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9)
       RETURNING *`,
      [
        approvalId,
        mission.id,
        artifactIds,
        requestedBy,
        new Date(),
        'pending',
        mission.priority,
        dueAt,
        false
      ]
    );

    await this.updateMissionStatus(mission.id, MissionStatus.AWAITING_APPROVAL);

    logger.info('Publisher: Approval requested', {
      approvalId,
      missionId: mission.id,
      dueAt
    });

    return this.mapRowToApproval(result.rows[0]);
  }

  async handleApprovalDecision(
    approvalId: string,
    approved: boolean,
    userId: string,
    comments?: string
  ): Promise<{ success: boolean; mission?: AgentMission }> {
    logger.info('Publisher: Handling approval decision', {
      approvalId,
      approved,
      userId
    });

    const approval = await this.getApproval(approvalId);
    if (!approval) {
      throw new Error('Approval not found');
    }

    if (approval.status !== 'pending') {
      throw new Error('Approval already processed');
    }

    const now = new Date();
    const updateQuery = approved ?
      `UPDATE agent_approvals 
       SET status = $1, approved_by = $2, approved_at = $3, comments = $4
       WHERE id = $5 RETURNING *` :
      `UPDATE agent_approvals 
       SET status = $1, rejected_by = $2, rejected_at = $3, rejection_reason = $4
       WHERE id = $5 RETURNING *`;

    const result = await database.query(updateQuery, approved ?
      ['approved', userId, now, JSON.stringify(comments ? [{ user_id: userId, content: comments, created_at: now }] : []), approvalId] :
      ['rejected', userId, now, comments, approvalId]
    );

    if (approved) {
      await this.updateMissionStatus(approval.mission_id, MissionStatus.APPROVED);
      
      const missionResult = await database.query(
        'SELECT * FROM agent_missions WHERE id = $1',
        [approval.mission_id]
      );

      return { success: true, mission: missionResult.rows[0] };
    } else {
      await this.updateMissionStatus(approval.mission_id, MissionStatus.REJECTED);
      return { success: true };
    }
  }

  private async getApproval(approvalId: string): Promise<AgentApproval | null> {
    const result = await database.query(
      'SELECT * FROM agent_approvals WHERE id = $1',
      [approvalId]
    );

    if (result.rows.length === 0) {
      return null;
    }

    return this.mapRowToApproval(result.rows[0]);
  }

  private async updateMissionStatus(missionId: string, status: MissionStatus): Promise<void> {
    await database.query(
      `UPDATE agent_missions 
       SET status = $1, updated_at = $2
       WHERE id = $3`,
      [status, new Date(), missionId]
    );
  }

  private mapRowToApproval(row: any): AgentApproval {
    return {
      id: row.id,
      mission_id: row.mission_id,
      artifact_ids: row.artifact_ids || [],
      requested_by: row.requested_by,
      requested_at: row.requested_at,
      approved_by: row.approved_by,
      approved_at: row.approved_at,
      rejected_by: row.rejected_by,
      rejected_at: row.rejected_at,
      rejection_reason: row.rejection_reason,
      status: row.status,
      priority: row.priority,
      due_at: row.due_at,
      notification_sent: row.notification_sent,
      comments: typeof row.comments === 'string' ? JSON.parse(row.comments) : row.comments || []
    };
  }
}

export default new PublisherService();
