import { NextRequest, NextResponse } from 'next/server';
import fs from 'fs/promises';
import path from 'path';
import { getMonorepoRoot } from '@/lib/repo-root';
import { BASELINE_EDGE_IDS, BASELINE_NODE_IDS } from '@/components/system-architecture/architecture-data';
import {
  buildWiringSuggestionsMarkdown,
  buildComposeFragmentCommentary,
  buildProposedEdgeManifestEntries,
} from '@/lib/architecture/wiring-suggestions';
import type { LayoutNode, LayoutEdge } from '@/lib/architecture/wiring-suggestions';

export const runtime = 'nodejs';

function assertWriteAllowed(req: NextRequest): boolean {
  const secret = process.env.ARCHITECTURE_WRITE_SECRET;
  if (!secret) return true;
  return req.headers.get('x-architecture-secret') === secret;
}

function buildApplyPs1(): string {
  return `# Auto-generated by Portal UI — System Architecture
# Finds repo root (docker-compose.dev.yml) and rebuilds the dev stack.
$ErrorActionPreference = 'Stop'
$here = $PSScriptRoot
$root = $here
while ($root -and -not (Test-Path (Join-Path $root "docker-compose.dev.yml"))) {
  $parent = Split-Path $root -Parent
  if ($parent -eq $root) { throw "Could not find repo root (docker-compose.dev.yml)" }
  $root = $parent
}
Set-Location $root
Write-Host "== apply-wiring: repo root = $root ==" -ForegroundColor Cyan
if (-not (Get-Command docker -ErrorAction SilentlyContinue)) {
  throw "docker CLI not found on PATH"
}
Write-Host "docker compose -f docker-compose.dev.yml build --parallel" -ForegroundColor Yellow
docker compose -f docker-compose.dev.yml build --parallel
Write-Host "docker compose -f docker-compose.dev.yml up -d" -ForegroundColor Yellow
docker compose -f docker-compose.dev.yml up -d
Write-Host "Done." -ForegroundColor Green
`;
}

function buildApplySh(): string {
  return `#!/usr/bin/env bash
set -euo pipefail
# Auto-generated by Portal UI — System Architecture
HERE="$(cd "$(dirname "$0")" && pwd)"
ROOT="$HERE"
while [ ! -f "$ROOT/docker-compose.dev.yml" ]; do
  PARENT="$(dirname "$ROOT")"
  if [ "$PARENT" = "$ROOT" ]; then echo "Could not find repo root"; exit 1; fi
  ROOT="$PARENT"
done
cd "$ROOT"
echo "== apply-wiring: repo root = $ROOT =="
command -v docker >/dev/null || { echo "docker not found"; exit 1; }
docker compose -f docker-compose.dev.yml build --parallel
docker compose -f docker-compose.dev.yml up -d
echo "Done."
`;
}

export async function POST(req: NextRequest) {
  if (!assertWriteAllowed(req)) {
    return NextResponse.json(
      { error: 'Unauthorized: set x-architecture-secret or unset ARCHITECTURE_WRITE_SECRET for local dev' },
      { status: 401 },
    );
  }

  let body: { nodes?: unknown[]; edges?: unknown[] };
  try {
    body = await req.json();
  } catch {
    return NextResponse.json({ error: 'Invalid JSON' }, { status: 400 });
  }

  if (!Array.isArray(body.nodes) || !Array.isArray(body.edges)) {
    return NextResponse.json({ error: 'nodes and edges arrays required' }, { status: 400 });
  }

  const root = getMonorepoRoot();
  const outDir = path.join(root, 'generated', 'architecture', 'outputs');
  const scriptsDir = path.join(outDir, 'scripts');

  await fs.mkdir(scriptsDir, { recursive: true });

  const generatedAt = new Date().toISOString();
  const layout = { generatedAt, nodes: body.nodes, edges: body.edges };

  const nodeList = (body.nodes as { id?: string; data?: { label?: string; sub?: string } }[])
    .map((n) => ({
      id: n.id,
      label: n.data?.label ?? n.id,
      path: n.data?.sub,
    }))
    .filter((n) => n.id);

  const nodesTyped = body.nodes as LayoutNode[];
  const edgesTyped = body.edges as LayoutEdge[];

  const extraNodeSubs = nodesTyped
    .filter((n) => n.id && !BASELINE_NODE_IDS.has(n.id!))
    .map((n) => n.data?.sub)
    .filter((s): s is string => typeof s === 'string' && s.length > 0);

  const suggestionsMd = buildWiringSuggestionsMarkdown(
    nodesTyped,
    edgesTyped,
    BASELINE_EDGE_IDS,
    BASELINE_NODE_IDS,
    generatedAt,
  );

  const fragmentYml = buildComposeFragmentCommentary(extraNodeSubs, generatedAt);

  const proposedEdges = buildProposedEdgeManifestEntries(nodesTyped, edgesTyped, BASELINE_EDGE_IDS);

  const edges = body.edges as { id?: string; source?: string; target?: string; label?: string }[];
  const manifest = {
    generatedAt,
    summary: {
      nodeCount: nodeList.length,
      edgeCount: edges.length,
      proposedEdgeCount: proposedEdges.length,
    },
    nodes: nodeList,
    edges: edges.map((e) => ({
      id: e.id,
      from: e.source,
      to: e.target,
      label: e.label,
    })),
    proposedEdges,
    note: 'Review before apply. proposedEdges.composeHints are advisory; implement in docker-compose or service env as needed.',
  };

  await fs.writeFile(path.join(outDir, 'layout.json'), JSON.stringify(layout, null, 2), 'utf8');
  await fs.writeFile(path.join(outDir, 'wiring-manifest.json'), JSON.stringify(manifest, null, 2), 'utf8');
  await fs.writeFile(path.join(outDir, 'wiring-suggestions.md'), suggestionsMd, 'utf8');
  await fs.writeFile(path.join(outDir, 'docker-compose.fragment.yml'), fragmentYml, 'utf8');
  await fs.writeFile(path.join(scriptsDir, 'apply-wiring.ps1'), buildApplyPs1(), 'utf8');
  await fs.writeFile(path.join(scriptsDir, 'apply-wiring.sh'), buildApplySh(), 'utf8');

  try {
    await fs.chmod(path.join(scriptsDir, 'apply-wiring.sh'), 0o755);
  } catch {
    /* windows */
  }

  return NextResponse.json({
    ok: true,
    root,
    written: [
      'generated/architecture/outputs/layout.json',
      'generated/architecture/outputs/wiring-manifest.json',
      'generated/architecture/outputs/wiring-suggestions.md',
      'generated/architecture/outputs/docker-compose.fragment.yml',
      'generated/architecture/outputs/scripts/apply-wiring.ps1',
      'generated/architecture/outputs/scripts/apply-wiring.sh',
    ],
  });
}
