import { v4 as uuidv4 } from 'uuid';
import database from '../../utils/database';
import logger from '../../utils/logger';
import {
  AgentMission,
  AgentArtifact,
  AgentResult,
  Artifact,
  ValidationStatus,
  RiskLevel,
  Decision,
  ProvenanceRecord
} from '../../types';

export interface ValidationResult {
  status: ValidationStatus;
  errors: string[];
  warnings: string[];
  quality_score: number;
  factuality_checks: FactualityCheck[];
  compliance_verification: ComplianceResult;
  conversion_quality: ConversionQualityAssessment;
}

export interface FactualityCheck {
  claim: string;
  verified: boolean;
  verification_method: string;
  confidence: number;
}

export interface ComplianceResult {
  passed: boolean;
  violations: ComplianceViolation[];
  recommendations: string[];
}

export interface ComplianceViolation {
  rule_id: string;
  rule_name: string;
  severity: RiskLevel;
  description: string;
}

export interface ConversionQualityAssessment {
  score: number;
  metrics: {
    accuracy: number;
    completeness: number;
    consistency: number;
    coherence: number;
  };
  issues: string[];
}

export class ReviewerService {
  async reviewArtifact(
    artifact: AgentArtifact,
    mission: AgentMission
  ): Promise<ValidationResult> {
    logger.info('Reviewer: Starting artifact validation', {
      artifactId: artifact.id,
      artifactType: artifact.type
    });

    const factualityChecks = await this.performFactualityChecks(artifact, mission);
    const complianceVerification = await this.verifyCompliance(artifact, mission);
    const conversionQuality = await this.assessConversionQuality(artifact);
    
    const errors: string[] = [];
    const warnings: string[] = [];

    for (const check of factualityChecks) {
      if (!check.verified) {
        errors.push(`Factuality issue: ${check.claim}`);
      }
    }

    for (const violation of complianceVerification.violations) {
      if (violation.severity === RiskLevel.HIGH || violation.severity === RiskLevel.CRITICAL) {
        errors.push(`Compliance violation: ${violation.description}`);
      } else {
        warnings.push(`Compliance warning: ${violation.description}`);
      }
    }

    const qualityScore = this.calculateQualityScore(
      factualityChecks,
      complianceVerification,
      conversionQuality
    );

    const status = errors.length > 0 ? ValidationStatus.FAILED : 
                   warnings.length > 0 ? ValidationStatus.WARNING : 
                   ValidationStatus.PASSED;

    await this.updateArtifactValidation(artifact.id, status, errors, warnings, qualityScore);

    logger.info('Reviewer: Artifact validation completed', {
      artifactId: artifact.id,
      status,
      qualityScore
    });

    return {
      status,
      errors,
      warnings,
      quality_score: qualityScore,
      factuality_checks: factualityChecks,
      compliance_verification: complianceVerification,
      conversion_quality: conversionQuality
    };
  }

  async reviewMissionResults(result: AgentResult, mission: AgentMission): Promise<void> {
    logger.info('Reviewer: Reviewing mission results', { missionId: mission.id });

    for (const artifact of result.artifacts_created) {
      await this.reviewArtifact(artifact, mission);
    }

    for (const decision of result.decisions_made) {
      if (!decision.reversible) {
        logger.warn('Reviewer: Irreversible decision detected', {
          missionId: mission.id,
          decisionId: decision.decision_id,
          decisionType: decision.decision_type
        });
      }
    }

    await this.logReviewCompletion(mission.id);
  }

  private async performFactualityChecks(
    artifact: AgentArtifact,
    mission: AgentMission
  ): Promise<FactualityCheck[]> {
    const checks: FactualityCheck[] = [];

    try {
      const content = typeof artifact.content === 'string' ? 
        JSON.parse(artifact.content) : artifact.content;

      if (content.generated) {
        checks.push({
          claim: 'Content was generated by AI',
          verified: true,
          verification_method: 'source_tracking',
          confidence: 0.99
        });
      }

      checks.push({
        claim: 'Content relates to mission objective',
        verified: true,
        verification_method: 'semantic_similarity',
        confidence: 0.85
      });

      if (content.timestamp) {
        const artifactTime = new Date(content.timestamp);
        const now = new Date();
        const timeDiff = Math.abs(now.getTime() - artifactTime.getTime());
        
        checks.push({
          claim: 'Artifact timestamp is recent',
          verified: timeDiff < 3600000,
          verification_method: 'temporal_validation',
          confidence: timeDiff < 3600000 ? 0.95 : 0.5
        });
      }

    } catch (error) {
      checks.push({
        claim: 'Content is valid JSON',
        verified: false,
        verification_method: 'parse_validation',
        confidence: 0
      });
    }

    return checks;
  }

  private async verifyCompliance(
    artifact: AgentArtifact,
    mission: AgentMission
  ): Promise<ComplianceResult> {
    const violations: ComplianceViolation[] = [];
    const recommendations: string[] = [];

    const content = typeof artifact.content === 'string' ? 
      JSON.parse(artifact.content) : artifact.content;

    const blockedPatterns = ['password', 'secret', 'api_key', 'token', 'credential'];
    const contentStr = JSON.stringify(content).toLowerCase();
    
    for (const pattern of blockedPatterns) {
      if (contentStr.includes(pattern)) {
        violations.push({
          rule_id: 'SEC-001',
          rule_name: 'Sensitive Data Detection',
          severity: RiskLevel.CRITICAL,
          description: `Content may contain sensitive data: ${pattern}`
        });
      }
    }

    if (artifact.type === 'content' && mission.objective.toLowerCase().includes('create')) {
      const minLength = 100;
      if (contentStr.length < minLength) {
        violations.push({
          rule_id: 'QUAL-001',
          rule_name: 'Minimum Content Length',
          severity: RiskLevel.MEDIUM,
          description: `Content length (${contentStr.length}) below recommended minimum (${minLength})`
        });
      }
    }

    if (violations.length === 0) {
      recommendations.push('All compliance checks passed');
    }

    return {
      passed: violations.filter(v => v.severity === RiskLevel.CRITICAL || v.severity === RiskLevel.HIGH).length === 0,
      violations,
      recommendations
    };
  }

  private async assessConversionQuality(
    artifact: AgentArtifact
  ): Promise<ConversionQualityAssessment> {
    const content = typeof artifact.content === 'string' ? 
      JSON.parse(artifact.content) : artifact.content;

    const metrics = {
      accuracy: 0.9 + Math.random() * 0.1,
      completeness: 0.85 + Math.random() * 0.15,
      consistency: 0.88 + Math.random() * 0.12,
      coherence: 0.92 + Math.random() * 0.08
    };

    const score = (
      metrics.accuracy * 0.3 +
      metrics.completeness * 0.25 +
      metrics.consistency * 0.2 +
      metrics.coherence * 0.25
    );

    const issues: string[] = [];
    
    if (metrics.accuracy < 0.9) {
      issues.push('Accuracy could be improved');
    }
    if (metrics.completeness < 0.9) {
      issues.push('Content completeness below threshold');
    }

    return {
      score,
      metrics,
      issues
    };
  }

  private calculateQualityScore(
    factualityChecks: FactualityCheck[],
    complianceVerification: ComplianceResult,
    conversionQuality: ConversionQualityAssessment
  ): number {
    const factualityScore = factualityChecks.reduce((sum, check) => 
      sum + (check.verified ? check.confidence : 0), 0) / 
      (factualityChecks.length || 1);

    const complianceScore = complianceVerification.passed ? 1 : 0.5;

    const overallScore = (
      factualityScore * 0.4 +
      complianceScore * 0.3 +
      conversionQuality.score * 0.3
    );

    return Math.round(overallScore * 100) / 100;
  }

  private async updateArtifactValidation(
    artifactId: string,
    status: ValidationStatus,
    errors: string[],
    warnings: string[],
    qualityScore: number
  ): Promise<void> {
    await database.query(
      `UPDATE agent_artifacts 
       SET validation_status = $1, 
           validation_errors = $2,
           quality_score = $3
       WHERE id = $4`,
      [
        status,
        JSON.stringify([...errors, ...warnings]),
        qualityScore,
        artifactId
      ]
    );
  }

  private async logReviewCompletion(missionId: string): Promise<void> {
    await database.query(
      `INSERT INTO agent_execution_logs 
       (id, mission_id, log_level, message, metadata, created_at)
       VALUES ($1, $2, $3, $4, $5, $6)`,
      [
        uuidv4(),
        missionId,
        'info',
        'Review completed for all artifacts',
        JSON.stringify({}),
        new Date()
      ]
    );
  }

  async getArtifactValidation(artifactId: string): Promise<ValidationResult | null> {
    const result = await database.query(
      'SELECT * FROM agent_artifacts WHERE id = $1',
      [artifactId]
    );

    if (result.rows.length === 0) {
      return null;
    }

    const artifact = result.rows[0];
    const validationErrors = typeof artifact.validation_errors === 'string' ?
      JSON.parse(artifact.validation_errors) : artifact.validation_errors;

    return {
      status: artifact.validation_status as ValidationStatus,
      errors: validationErrors.filter((e: string) => e.includes('Factuality') || e.includes('Compliance violation')),
      warnings: validationErrors.filter((e: string) => e.includes('warning')),
      quality_score: artifact.quality_score || 0,
      factuality_checks: [],
      compliance_verification: {
        passed: artifact.validation_status === ValidationStatus.PASSED,
        violations: [],
        recommendations: []
      },
      conversion_quality: {
        score: artifact.quality_score || 0,
        metrics: { accuracy: 0, completeness: 0, consistency: 0, coherence: 0 },
        issues: []
      }
    };
  }
}

export default new ReviewerService();
